Repository BigData23th/DeepLearning, pull requests merged in 2023-04, with the labels that each got.

#32 2023_03_31_회고
  cc5547/2023_03_30_ch09_DL_02_ANN.ipynb
  cc5547/2023_03_31_ch09_DL_03_DNN.ipynb
  cc5547/2023_03_31_ch09_DL_04_CNN_ipynb의.ipynb
  cc5547/2023_03_31_ch09_DL_05_ResNet.ipynb
Labels: 네줄일기

#37 230403 회고...
  tkd8973/ANN_DNN_PYTORCH_GPT.ipynb
  tkd8973/DL_DNN_ipynb의_사본.ipynb
  tkd8973/Plant_Imload.ipynb
  tkd8973/지피티야_도와줘.ipynb
Labels: KPT

#39 2023_04_03_회고
  cc5547/2023_04_03_ch_GPT_활용.ipynb
Labels: 네줄일기

#47 4/3회고
  whataLIN/ch09_DL_06_전이학습_qus0in_잎사귀_EDA.ipynb
Labels: 네줄일기

#51 2023.04.04 회고
  hiid0726/ch09_DL_07_오토인코더_ym.ipynb
  hiid0726/ch09_DL_08_GAN_ym.ipynb
  hiid0726/ch09_DL_09_cGAN_ym.ipynb
Labels: 네줄일기

#52 26일차 회고
  jaiwon880/DeepLearning_GAN.ipynb
  jaiwon880/DeepLearning_cGAN.ipynb
  jaiwon880/DeepLearning_오토인코더(비지도학습).ipynb
Labels: KPT

#53 04.04 회고
  jyeongvv/DL_08_GAN.ipynb
  jyeongvv/DL_cGAN_.ipynb
  jyeongvv/DL_오토인코더.ipynb
Labels: KPT

#54 회고
  jinu/CH09_06.ipynb
  jinu/ch09_DL_07_오토인코더.ipynb
  jinu/ch09_DL_08_GAN.ipynb
  jinu/ch09_DL_09_cGAN.ipynb
Labels: 네줄일기

#56 2023/04/04
  JoySoon/ch09_DL_07_오토인코더_KSW.ipynb
  JoySoon/ch09_DL_08_GAN_KSW.ipynb
  JoySoon/ch09_DL_09_cGAN_KSW.ipynb
Labels: 네줄일기

#58 2023.04.04 회고
  mastgm0817/cats_and_dogs_이진분류모델.ipynb
  mastgm0817/ch09_DL_07_오토인코더.ipynb
  mastgm0817/ch09_DL_08_GAN.ipynb
  mastgm0817/ch09_DL_09_cGAN.ipynb
Labels: 네줄일기

#59 23.04.04 수업 회고
  JaejinLee1215/ch09_DL_06_전이학습_이재진_잎사귀_Baseline.ipynb
  JaejinLee1215/ch09_DL_07_오토인코더_이재진.ipynb
  JaejinLee1215/ch09_DL_08_GAN_이재진.ipynb
  JaejinLee1215/ch09_DL_09_cGAN_이재진.ipynb
Labels: STAR

#60 0404 회고
  sunghuncho/ch09_DL_07_오토인코더_sunghuncho.ipynb
  sunghuncho/ch09_DL_08_GAN_sunghuncho.ipynb
  sunghuncho/ch09_DL_09_cGAN_sunghuncho.ipynb
Labels: 네줄일기

#66 27일차 회고
  jaiwon880/09_02_review.ipynb
  jaiwon880/DeepLearning_RNN.ipynb
Labels: KPT

#67 회고
  jinu/ch09_07+08+09.ipynb
  jinu/ch09_DL_10_RNN.ipynb
  jinu/ch09_DL_11_RNN_TEXT.ipynb
Labels: 네줄일기

#68 2023/04/05 수업
  JoySoon/ch09_DL_10_RNN_KSW.ipynb
  JoySoon/ch09_DL_11_RNN_TEXT_KSW.ipynb
Labels: 네줄일기

#69 23.04.05 수업 회고
  JaejinLee1215/ch09_07+08+09_복습.ipynb
  JaejinLee1215/ch09_DL_10_RNN_이재진.ipynb
  JaejinLee1215/ch09_DL_11_RNN_TEXT_이재진.ipynb
  JaejinLee1215/prophet_이재진.ipynb
Labels: STAR

#71 0405 회고
  sunghuncho/ch09_DL_10_RNN_sunghuncho.ipynb
  sunghuncho/ch09_DL_11_RNN_TEXT_sunghuncho.ipynb
Labels: 네줄일기

#73 23.04.05
  zihvvan/ch09_07+08+09_복습.ipynb
  zihvvan/ch09_10+11_복습.ipynb
  zihvvan/ch09_DL_10_RNN.ipynb
  zihvvan/ch09_DL_11_RNN_TEXT.ipynb
  zihvvan/ch09_DL_12_LSTM.ipynb
Labels: 네줄일기

#74 23. 04. 05 회고
  CHOISEONGGU/공부자료/220329_prophet_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch09_DL_07_오토인코더_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch09_DL_08_GAN_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch09_DL_09_cGAN_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch09_DL_10_RNN_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch09_DL_11_RNN_TEXT_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch09_DL_12_LSTM_ChoiSG.ipynb
  CHOISEONGGU/복습/ch09_07+08+09_복습.ipynb
  CHOISEONGGU/복습/ch09_10+11_복습.ipynb
Labels: 네줄일기

#75 2023.04.05 회고
  mastgm0817/ch09_DL_10_RNN.ipynb
  mastgm0817/ch09_DL_11_RNN.ipynb
Labels: 네줄일기

#76 28일차 회고
  jaiwon880/DeepLearning_LSTM.ipynb
Labels: KPT

#77 04.06 회고
  jyeongvv/DL_LSTM.ipynb
Labels: KPT

#78 04-06 회고
  kwa99/ch09_10+11.ipynb
  kwa99/ch09_DL_12_LSTM_wa99.ipynb
Labels: KPT

#79 4월 6일
  Yeaaaaaaah/220329_prophet_!.ipynb
  Yeaaaaaaah/TTS_프로젝트_참고.ipynb
  Yeaaaaaaah/ch09_DL_10_RNN_!.ipynb
  Yeaaaaaaah/ch09_DL_11_RNN_TEXT_!.ipynb
  Yeaaaaaaah/ch09_DL_12_LSTM_!.ipynb
Labels: KPT

#81 회고
  jinu/ch09_10+11.ipynb
  jinu/ch09_DL_12_LSTM.ipynb
Labels: 네줄일기

#82 0406 회고
  sunghuncho/ch09_DL_12_LSTM_sunghuncho.ipynb
Labels: 네줄일기

#83 2023/04/06 수업
  JoySoon/ch09_DL_12_LSTM_KSW.ipynb
  JoySoon/ch09_DL_13_Seq2Seq_KSW.ipynb
Labels: STAR

#84 2023.04.06 회고
  mastgm0817/ch09_DL_12_LSTM.ipynb
Labels: 네줄일기

#85 04-06회고
  Myun9hyun/ch09_10+11.ipynb
  Myun9hyun/ch09_DL_13_Seq2Seq.ipynb
Labels: KPT
