Repository BigData23th/DeepLearning, pull requests merged in 2023-03, with the labels that each got.

#1 3월 30일 23일차 회고
  Yeaaaaaaah/ch09_DL_01_경사하강법.ipynb
  Yeaaaaaaah/ch09_DL_02_ANN.ipynb
Labels: 네줄일기

#4 03-30 회고
  Myun9hyun/ch09_DL_01_경사하강법_qus0in.ipynb
  Myunghyun/ch09_DL_02_ANN.ipynb
  Myunghyun/ch09_DL_03_DNN.ipynb
Labels: KPT

#5 2023/03/30 수업
  JoySoon/ch09_DL_01_경사하강법_KSW.ipynb
  JoySoon/ch09_DL_02_ANN_KSW.ipynb
  JoySoon/ch09_DL_03_DNN_KSW.ipynb
Labels: 네줄일기

#6 0330
  andy9806/DNN.ipynb
  andy9806/경사하강법.ipynb
Labels: STAR

#7 2023_03_30_회고
  cc5547/2023_03_30_ch09_DL_01_경사하강법.ipynb
  cc5547/2023_03_30_ch09_DL_03_DNN.ipynb
Labels: 네줄일기

#8 2023.03.30 회고
  hiid0726/ch09_DL_01_경사하강법_ym.ipynb
  hiid0726/ch09_DL_02_ANN_ym.ipynb
  hiid0726/ch09_DL_03_DNN_ym_01.ipynb
Labels: 네줄일기

#9 2023.03.30 회고
  mastgm0817/ch09_DL_01_경사하강법.ipynb
  mastgm0817/ch09_DL_02_ANN.ipynb
  mastgm0817/ch09_DL_03_DNN_.ipynb
Labels: 네줄일기

#12 회고
  jinu/ch09_DL_01_경사하강법.ipynb
  jinu/ch09_DL_02_ANN.ipynb
Labels: 네줄일기

#11 23.03.30 수업 회고
  JaejinLee1215/ch09_DL_01_경사하강법_이재진.ipynb
  JaejinLee1215/ch09_DL_02_ANN_이재진.ipynb
  JaejinLee1215/ch09_DL_03_DNN_이재진.ipynb
Labels: STAR

#13 230330 회고
  tkd8973/DL_ANN.ipynb
  tkd8973/DL_DNN.ipynb
  tkd8973/DL_Torch_Gradient_Descent.ipynb
Labels: 네줄일기

#14 03-30 회고
  kwa99/ch09_DL_01_경사하강법_wa99.ipynb
  kwa99/ch09_DL_02_ANN_wa99.ipynb
  kwa99/ch09_DL_03_DNN_wa99.ipynb
Labels: 네줄일기

#15 2023.03.30
  zihvvan/ch09_DL_01_경사하강법.ipynb
  zihvvan/ch09_DL_02_ANN.ipynb
  zihvvan/ch09_DL_03_DNN.ipynb
Labels: 네줄일기

#16 0330 회고
  sunghuncho/ch09_DL_01_경사하강법_sunghuncho.ipynb
  sunghuncho/ch09_DL_02_ANN_sunghuncho.ipynb
  sunghuncho/ch09_DL_03_DNN_sunghuncho.ipynb
Labels: 네줄일기

#17 23.03.30 회고
  CHOISEONGGU/공부자료/ch09_DL_01_경사하강법_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch09_DL_02_ANN_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch09_DL_03_DNN_ChoiSG.ipynb
Labels: 네줄일기

#18 3.30 회고
  jyeongvv/ch09_DL_01_경사하강법.ipynb
  jyeongvv/ch09_DL_02_ANN.ipynb
  jyeongvv/ch09_DL_03_DNN.ipynb
Labels: KPT

#19 23일차 회고
  jaiwon880/DeepLearning_DNN.ipynb
  jaiwon880/ch09_DL_01_경사하강법.ipynb
  jaiwon880/ch09_DL_02_ANN.ipynb
Labels: KPT

#21 2023.03.31 회고
  hiid0726/ch09_DL_03_DNN_ym.ipynb
  hiid0726/ch09_DL_04_CNN_ym.ipynb
  hiid0726/ch09_DL_05_ResNet_ym.ipynb
Labels: 네줄일기

#22 2023/03/31 수업
  JoySoon/ch09_DL_03_DNN_KSW.ipynb
  JoySoon/ch09_DL_04_CNN_KSW.ipynb
  JoySoon/ch09_DL_05_ResNet_KSW.ipynb
Labels: KPT

#23 23. 03. 31 회고
  CHOISEONGGU/공부자료/ch09_DL_03_DNN_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch09_DL_04_CNN_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch09_DL_05_ResNet_ChoiSG.ipynb
  CHOISEONGGU/복습/ch09_01+02+03_복습.ipynb
Labels: 네줄일기

#24 day24
  jyeongvv/ch09_DL_03_DNN.ipynb
  jyeongvv/ch09_DL_04_CNN.ipynb
  jyeongvv/ch09_DL_05_ResNet.ipynb
Labels: KPT

#25 회
  jinu/ch09_01+02+03.ipynb
  jinu/ch09_DL_03_DNN.ipynb
  jinu/ch09_DL_04_CNN.ipynb
  jinu/ch09_DL_05_ResNet.ipynb
Labels: 네줄일기

#27 03-31회고
  Myun9hyun/ch09_01+02+03_복습.ipynb
  Myun9hyun/ch09_DL_02_ANN.ipynb
  Myun9hyun/ch09_DL_03_DNN.ipynb
  Myun9hyun/ch09_DL_04_CNN.ipynb
  Myun9hyun/ch09_DL_05_ResNet.ipynb
Labels: STAR

#28 0331 회고
  sunghuncho/ch09_01+02+03_복습.ipynb
  sunghuncho/ch09_DL_03_DNN_sunghuncho.ipynb
  sunghuncho/ch09_DL_04_CNN_sunghuncho.ipynb
  sunghuncho/ch09_DL_05_ResNet_sunghuncho.ipynb
Labels: 네줄일기

#30 2023.03.31
  zihvvan/ch09_01+02+03_복습.ipynb
  zihvvan/ch09_DL_03_DNN.ipynb
  zihvvan/ch09_DL_04_CNN.ipynb
  zihvvan/ch09_DL_05_ResNet.ipynb
Labels: 네줄일기

#31 2023.03.31 회고
  mastgm0817/ch09_DL_03_DNN.ipynb
  mastgm0817/ch09_DL_04_CNN.ipynb
  mastgm0817/ch09_DL_05_ResNet.ipynb
Labels: 네줄일기
